Added BooleanField field Type
davidbrownza/CORMAP pull request #32
Opened 2017-07-17 09:51 UTC by rowan08

Added the field to Field.h, Model.h and Model.cpp.
Also added to Model::insertBatch() to insert data for BOOL field types
Tested by adding a BooleanField, proteinIsDrugTarget, to test.cpp and setting the value to true. The script runs fine.
Issue: https://github.com/davidbrownza/CORMAP/issues/9

2017-07-18 18:45 UTC, davidbrownza commented on Model.cpp
> +                else if(f->getType() == BOOLEAN)
Just a side note, we should probably convert this if statement to a switch at some point in the future. Long term, there is a repeating pattern here that we could probably refactor.

2017-07-18 18:48 UTC, davidbrownza commented on Model.cpp
> +                else if(f->getType() == BOOLEAN)
For a start, the null check could be done before this if statement, which would mean we wouldn't have to repeat it within each block.

2017-07-18 18:52 UTC, davidbrownza requested changes
You did everything right, but I have added on an extra requirement :P

2017-07-18 18:52 UTC, davidbrownza commented on Model.cpp
> +                else if(f->getType() == BOOLEAN)
Actually, now is as good a time as any to do this. Convert this whole if statement to a switch and perform the null check before the switch.

2017-07-19 08:57 UTC, davidbrownza requested changes
Two small changes.

2017-07-19 08:57 UTC, davidbrownza commented on Model.cpp
> +                        {
Remove these brackets in the cases, they are not necessary.

2017-07-19 08:57 UTC, davidbrownza commented on Model.cpp
> +                } else {
You can remove the `else` block if you use a `continue` statement in the `if` block after setting the parameter to null.

2017-07-19 20:59 UTC, rowan08 commented on Model.cpp
> +                        {
If I remove the brackets (and nothing else), it throws errors along the lines of `error: jump to case label [-fpermissive]`,` error:   crosses initialization of ‘IntegerField* i’`  and ` error: conflicting declaration ‘BooleanField* i’ `.

This seems to have something to do with declaring variables within a switch statement, which is not allowed for reasons I don't entirely follow (see below...), but they recommend adding an additional layer of scope to fix this problem. 

https://stackoverflow.com/questions/449736/why-can-t-variables-be-declared-in-a-switch-statement

2017-07-20 16:46 UTC, davidbrownza requested changes

2017-07-20 16:46 UTC, davidbrownza commented on Model.cpp
> +                        {
Does it work if you move the `break` inside the brackets:
```
case INTEGER:
{
    IntegerField * i = static_cast <IntegerField*>(f);
    conn.setInt(paramNum, i->getValue());
    break;
}
```
If not, it is fine, just fix up the indentation like so:
```
case INTEGER:
    {
        IntegerField * i = static_cast <IntegerField*>(f);
        conn.setInt(paramNum, i->getValue());
    }
    break;
```

2017-07-21 14:53 UTC, davidbrownza approved these changes

2017-07-21 14:56 UTC, merged