Restructured directory structure and added makefile
davidbrownza/CORMAP pull request #37
Opened 2017-07-22 15:03 UTC by davidbrownza

2017-07-22 15:39 UTC, rowan08 requested changes
Just one small change - otherwise, looks good

2017-07-22 15:39 UTC, rowan08 commented on src/fields/Field.h
> +                throw std::length_error("Field value exeeds Max Length");
Change `std::length_error` back to `length_error`

2017-07-23 15:24 UTC, rowan08 requested changes
Couple of small changes, only one of which is definitely needed. 
I'm not sure what you want to do about the using namespace std; stuff, but have included all the scripts this was left out of.

2017-07-23 15:24 UTC, rowan08 commented on src/fields/CharField.h
> +};
No newline at end of file (apparently)

2017-07-23 15:24 UTC, rowan08 commented on src/fields/BooleanField.cpp
> +
For consistency, should `using namespace std;` be included in this file? 
Or removed from files: Field.h, BooleanField.h, etc.

2017-07-23 15:24 UTC, rowan08 commented on src/fields/CharField.cpp
> +
Add `using namespace std;` as mentioned above.

2017-07-23 15:24 UTC, rowan08 commented on src/fields/Field.cpp
> +
Add `using namespace std;` (as above)

2017-07-23 15:24 UTC, rowan08 commented on src/fields/FloatField.cpp
> +
Add `using namespace std;`

2017-07-23 15:24 UTC, rowan08 commented on src/fields/IntegerField.cpp
> +
Add `using namespace std;`

2017-07-23 15:24 UTC, rowan08 commented on src/fields/TextField.cpp
> +
Add `using namespace std;`

2017-07-23 15:24 UTC, rowan08 commented on src/fields/Field.h
> +        string fieldName;
I'm assuming we're tackling `string _fieldName`, etc in another issue?
Just mentioning in case it was supposed to be done here :P

2017-07-23 15:32 UTC, davidbrownza commented on src/fields/BooleanField.cpp
> +
It gets used in the `*.h` files, but not the `*.cpp` files.

2017-07-23 15:32 UTC, davidbrownza commented on src/fields/CharField.cpp
> +
Not necessary in the `*.cpp` files.

2017-07-23 15:33 UTC, davidbrownza commented on src/fields/CharField.h
> +};
Will fix.

2017-07-23 15:57 UTC, davidbrownza commented on src/fields/Field.cpp
> +
Not necessary in the `*.cpp` files.

2017-07-23 15:57 UTC, davidbrownza commented on src/fields/Field.h
> +        string fieldName;
Yep, this will be tackled in #34

2017-07-23 15:57 UTC, davidbrownza commented on src/fields/FloatField.cpp
> +
Not necessary in the `*.cpp` files.

2017-07-23 15:57 UTC, davidbrownza commented on src/fields/IntegerField.cpp
> +
Not necessary in the `*.cpp` files.

2017-07-23 15:57 UTC, davidbrownza commented on src/fields/TextField.cpp
> +
Not necessary in the `*.cpp` files.

2017-07-23 16:29 UTC, rowan08 approved these changes
Looks good

2017-07-23 16:43 UTC, merged